name: Linux Bazel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_with_bazel:
    strategy:
      matrix:
        mode: [ Release, Debug ]
    runs-on: [ ubuntu-22.04 ]

    steps:
      - uses: actions/checkout@v3

      - name: Clone Deps
        run: git submodule update --init
        working-directory: ${{github.workspace}}

      - name: Build
        run: bazel build \:all

      - name: Test
        run: bazel test \:all
