name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_on_macos:
    runs-on: macos-12
    strategy:
      matrix:
        mode: [ Release, Debug ]

    steps:
      - uses: actions/checkout@v3

      - name: Clone Deps
        run: git submodule update --init
        working-directory: ${{github.workspace}}

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.mode}}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}} -G Ninja -DUSE_CCACHE=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}} --verbose -j

      - name: Test
        working-directory: ${{github.workspace}}/build/test
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
